name: Symfony CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: gnp-formation2024
          MYSQL_USER: root
          MYSQL_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, pdo_mysql, xml, ctype, iconv, intl, zip
          tools: composer

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-scripts

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: teamflp/gnp-formationp:latest
          push: true

      - name: Run Docker container
        run: |
          docker run --name symfonyagnp-formation -d -p 8000:8000 --network host teamflp/gnp-formation:latest

      - name: Wait for application to be ready
        run: sleep 10  # Adjust sleep time as necessary

      - name: Run Symfony tests
        run: |
          docker exec gnp-formation php bin/phpunit

      - name: Stop and remove Docker container
        run: |
          docker stop gnp-formation
          docker rm gnp-formation

      - name: Remove Docker images
        run: |
          docker rmi teamflp/gnp-formation:latest

